baseURL = 'https://salimmajzoub.dev/'
languageCode = 'en-us'
title = "Salim's Blog"
theme = 'paper'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
    description = 'Senior Software Engineer at Cosmopoints | 1x AWS'
    name = 'Salim AlMajzoub'
    author = 'Salim AlMajzoub'
    bio = 'Senior Software Engineer at Cosmopoints | 1x AWS'
    avatar = 'https://github.com/salim-m.png'
    favicon = 'favicon.svg'

    # socials
    twitter = 'salim_majzoub'
    github = 'salim-m'
    linkedin = 'salim-majzoub'