baseURL = 'https://salimmajzoub.dev/'
languageCode = 'en-us'
title = 'Salim Majzoub'
theme = 'paper'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
    description = 'Documenting my journey through the stack... and the mess'

    # socials
    twitter = 'salim_majzoub'
    github = 'salim-m'
    linkedin = 'salim-majzoub'